In [59]:
# Wine reviews dataset from Kaggle

import pandas as pd
import numpy as np

w_reviews = pd.read_csv(r'C:\Users\Bharat\Downloads\winemag-data-130k-v2\wine_rev.csv')

In [60]:
w_reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [14]:
n_trop = w_reviews.description.map(lambda desc: "tropical" in desc).sum()
n_trop

3607

In [16]:
n_fruits = w_reviews.description.map(lambda desc:"fruity" in desc).sum()
n_fruits

9090

In [19]:
descriptor_counts = pd.Series([n_trop, n_fruits], index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [20]:
w_reviews.country.value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Czech Republic               12
Macedonia                    12
Serbia                       12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: country, dtype: int64

We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series star_ratings with the number of stars corresponding to each review in the dataset.

In [24]:
def stars(row):
    if row.country == "Canada":
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >=85 and row.points < 95:
        return 3
    else:
        return 1
    
star_ratings = w_reviews.apply(stars, axis = 'columns')

In [26]:
star_ratings

0         3
1         3
2         3
3         3
4         3
         ..
129966    3
129967    3
129968    3
129969    3
129970    3
Length: 129971, dtype: int64

In [34]:
w_reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [35]:
w_reviews.points.value_counts()

88     17207
87     16933
90     15410
86     12600
89     12226
91     11359
92      9613
85      9530
93      6489
84      6480
94      3758
83      3025
82      1836
95      1535
81       692
96       523
80       397
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [36]:
w_reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [54]:
w_reviews.groupby(["country","province"]).apply(lambda df:df.loc[df.points.idxmax()])

                            Unnamed: 0    country  \
country   province
Argentina Mendoza Province       82754  Argentina
          Other                  78303  Argentina
Armenia   Armenia                66146    Armenia
Australia Australia Other        37882  Australia
          New South Wales        85337  Australia
...                                ...        ...
Uruguay   Juanico                 9133    Uruguay
          Montevideo             15750    Uruguay
          Progreso               93103    Uruguay
          San Jose               39898    Uruguay
          Uruguay                39361    Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 14 columns]

In [55]:
w_reviews.groupby(['country']).price.agg([len,min,max])

                            len   min     max
country
Argentina                3800.0   4.0   230.0
Armenia                     2.0  14.0    15.0
Australia                2329.0   5.0   850.0
Austria                  3345.0   7.0  1100.0
Bosnia and Herzegovina      2.0  12.0    13.0
Brazil                     52.0  10.0    60.0
Bulgaria                  141.0   8.0   100.0
Canada                    257.0  12.0   120.0
Chile                    4472.0   5.0   400.0
China                       1.0  18.0    18.0
Croatia                    73.0  12.0    65.0
Cyprus                     11.0  11.0    21.0
Czech Republic             12.0  15.0    45.0
Egypt                       1.0   NaN     NaN
England                    74.0  25.0    95.0
France                  22093.0   5.0  3300.0
Georgia                    86.0   9.0    40.0
Germany                  2165.0   5.0   775.0
Greece                    466.0   8.0    79.0
Hungary                   146.0  10.0   764.0
India                       9.0  10.0    20.0
Israel                    505.0   8.0   150.0
Italy                   19540.0   5.0   900.0
Lebanon                    35.0  13.0    75.0
Luxembourg                  6.0  16.0    30.0
Macedonia                  12.0  15.0    20.0
Mexico                     70.0   8.0   108.0
Moldova                    59.0   8.0    42.0
Morocco                    28.0  14.0    40.0
New Zealand              1419.0   7.0   130.0
Peru                       16.0  10.0    68.0
Portugal                 5691.0   5.0  1000.0
Romania                   120.0   4.0   320.0
Serbia                     12.0  15.0    42.0
Slovakia                    1.0  16.0    16.0
Slovenia                   87.0   7.0    90.0
South Africa             1401.0   5.0   330.0
Spain                    6645.0   4.0   770.0
Switzerland                 7.0  21.0   160.0
Turkey                     90.0  14.0   120.0
US                      54504.0   4.0  2013.0
Ukraine                    14.0   6.0    13.0
Uruguay                   109.0  10.0   130.0

In [63]:
w_reviews.groupby(['taster_twitter_handle']).taster_name.count()

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_name, dtype: int64

In [76]:
w_reviews.groupby('price').points.max().sort_index()

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [80]:
w_reviews.groupby(['country','variety']).size().sort_values(ascending=False)

country    variety
US         Pinot Noir                  9885
           Cabernet Sauvignon          7315
           Chardonnay                  6801
France     Bordeaux-style Red Blend    4725
Italy      Red Blend                   3624
                                       ...
Uruguay    Tempranillo-Tannat             1
Italy      Pignolo                        1
           Muscat                         1
           Moscato di Noto                1
Argentina  Barbera                        1
Length: 1612, dtype: int64

In [100]:
 w_reviews.region_1.fillna("Unknown").value_counts().sort_values(ascending=False)

Unknown                           21247
Napa Valley                        4480
Columbia Valley (WA)               4124
Russian River Valley               3091
California                         2629
                                  ...
Lamezia                               1
Côtes de Forez                        1
Paso Robles Highlands District        1
Henty                                 1
Mitterberg                            1
Name: region_1, Length: 1230, dtype: int64